--- 
kind: pipeline
name: anu
steps: 
  - name: nganu
    image: "rikorose/gcc-cmake:gcc-10"
    commands: 
      - "apt update -qqy && apt install git wget -qqy"
      - "git clone $REPOS anu"
      - "rm -rf .git"
      - "cd anu"
      - "bash build.sh"
    environment: 
      REPOS: 
        from_secret: REPOS
